var element1 = document.getElementById('btn2');
console.log(element1);
var element2 = document.getElementsByClassName('main');
console.log(element2);
var element3 = document.querySelector('#btn2');
console.log(element3);
var element4 = document.querySelector('.main');
console.log(element4);
var elements1 = document.querySelectorAll('.main');
console.log(elements1);
var elements2 = document.getElementsByTagName('div');
console.log(elements2);
var elements3 = document.getElementsByName('p');
console.log(elements3);
var test = document.getElementById('test');
test.innerHTML = 'Testando Typescript';
//test.textContent = 'Testando Typescript';
var novadiv = document.createElement('div');
novadiv.textContent = 'Typescript + Javascript';
test.appendChild(novadiv);
test.insertBefore(novadiv, test.firstChild);
